M48
; DRILL file {KiCad 9.0.3-1.fc42app2} date 2025-10-05T13:47:22+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-05T13:47:22+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-1.fc42app2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X95.784Y-129.501
X95.784Y-135.281
T2
X330.16Y-54.095
M30
